<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\PaymobWebhook\**" />
    <EmbeddedResource Remove="Controllers\PaymobWebhook\**" />
    <None Remove="Controllers\PaymobWebhook\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Services.Abstractions\Services.Abstractions.csproj" />
  </ItemGroup>

</Project>
