using Domain.Entities.Common;
using Domain.Entities.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.Entities.BusinessEntities
{
    public class PaymentRefund : BaseEntity<int>
    {
        public int PaymentId { get; set; }
        public Payment Payment { get; set; } = null!;


        /// <summary>
        /// Unique key generated by Clinova for this refund operation.
        /// Used to guarantee idempotency inside our system.
        /// </summary>
        public string IdempotencyKey { get; set; } = null!;


        public RefundReason Reason { get; set; }

        public RefundStatus Status { get; set; }


        /// <summary>
        /// Amount that Clinova requested to refund in EGP.
        /// </summary>
        public decimal Amount { get; set; }


        /// <summary>
        /// Paymob transaction ID of the original successful payment.
        /// </summary>
        public string OriginalTransactionId { get; set; } = null!;


        /// <summary>
        /// Paymob refund transaction ID if Paymob provides one.
        /// </summary>
        public string? ProviderRefundTransactionId { get; set; }


        public DateTime RequestedAt { get; set; }

        public DateTime? ProcessedAt { get; set; }

        public string? FailureReason { get; set; }

        public string? ProviderResponse { get; set; }


        /// <summary>
        /// Used to protect refund state transitions from concurrent requests.
        /// This is important because a payment must never be refunded twice
        /// because of concurrent application requests.
        /// </summary>
        public byte[] RowVersion { get; set; } = null!;
    }
}
